### PR TITLE
[FIX] Wrong pluralization of "stadium"

### LINKED ISSUE #247: Wrong Pluralization of "stadium"
The plural of `stadium` should be `stadiums` and not `stadia`.

### PR DESCRIPTION
**Pull request by thrashzone13**
Fixes #247

### CODE REVIEW

File: lib/Doctrine/Inflector/Rules/English/Inflectible.php [hunk 1]
```diff
@@ -173,12 +173,12 @@ public static function getIrregular(): iterable
         yield new Substitution(new Word('foe'), new Word('foes'));
         yield new Substitution(new Word('grave'), new Word('graves'));
         yield new Substitution(new Word('hoax'), new Word('hoaxes'));
-        yield new Substitution(new Word('medium'), new Word('media'));
```
Comment (greg0ire) [inline lib/Doctrine/Inflector/Rules/English/Inflectible.php:176]: Should we sort the list, so as to avoid such duplicates?

Comment (thrashzone13) [reply lib/Doctrine/Inflector/Rules/English/Inflectible.php:176]: I was wondering as well ... I'll do it

**Comment by greg0ire** [comment]
Thanks @thrashzone13 !
